/**
 * Wikipedia Image Fetcher
 * Fetches diagram/image URLs from Wikipedia for a given topic.
 * Uses Wikipedia REST API (summary endpoint) and MediaWiki API as fallback.
 */

export interface WikiImage {
  url: string;
  caption: string;
  sourceUrl: string;
}

/**
 * Normalizes Wikimedia Commons URLs to use an allowed thumbnail size (e.g. 500px)
 * to prevent 400 Bad Request errors caused by Wikimedia's thumbnail size allowlist.
 */
function getWikimediaThumbnailUrl(originalUrl: string, size = 500): string {
  // Just return the original URL which is guaranteed to be valid by the API.
  // Manually rewriting to 500px causes 400/404 errors if that specific thumbnail size bucket is not generated by Wikimedia.
  return originalUrl;
}

/**
 * Fetches the best available image for a Wikipedia article title.
 * Tries REST summary API first, then MediaWiki pageimages API as fallback.
 */
/**
 * Cleans raw Wikipedia titles to ensure successful queries.
 * Strips parentheses, non-ASCII/Devanagari characters, and extra symbols.
 */
function cleanWikipediaTitle(wikiTitle: string): string {
  return wikiTitle
    .replace(/\([^)]*\)/g, "") // Remove contents inside parentheses (like "(जड़त्व)" or "(Hindi explanation)")
    .replace(/[^\x00-\x7F]/g, "") // Remove Devanagari / non-ASCII characters
    .replace(/[^a-zA-Z0-9\s\-_\']/g, "") // Remove special symbols (keep alphanumeric, space, hyphen, underscore, single quote)
    .replace(/\s+/g, " ") // Clean up duplicate spaces
    .trim();
}

/**
 * Searches Wikipedia to find the closest matching real article title.
 */
async function searchWikipediaTitle(cleanTitle: string): Promise<string | null> {
  try {
    const searchUrl = `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(cleanTitle)}&utf8=&format=json&origin=*`;
    const res = await fetch(searchUrl);
    if (res.ok) {
      const data = await res.json();
      const results = data.query?.search;
      if (results && results.length > 0) {
        return results[0].title;
      }
    }
  } catch {}
  return null;
}

/**
 * Helper to identify if an image is likely a biography photo, portrait painting, or historical monument
 * instead of an academic diagram/schematic.
 */
function isPhotoOrPortrait(url: string): boolean {
  const lowercaseUrl = url.toLowerCase();
  const PHOTO_BLACKLIST = [
    "portrait", "painting", "statue", "bust", "photo", "photograph", 
    "kneller", "signature", "tomb", "monument", "memorial", "grave",
    "stamp", "coin", "medal", "plaque", "face", "person", "man", "woman",
    "philosopher", "scientist", "physicist", "mathematician", "discoverer",
    "historical", "history", "biography", "birthplace", "house", "museum",
    "godfrey", "portraiture", "autograph"
  ];
  return PHOTO_BLACKLIST.some(term => lowercaseUrl.includes(term));
}

/**
 * Fetches the best available image for a Wikipedia article title.
 * Automatically cleans titles and performs a search-based fuzzy fallback if needed.
 */
export async function fetchWikipediaImage(wikiTitle: string): Promise<WikiImage | null> {
  const cleaned = cleanWikipediaTitle(wikiTitle);
  if (!cleaned) return null;

  let matchedTitle = cleaned;

  // Step 1: Direct fetch attempt
  let img = await tryFetchWikipediaImage(matchedTitle);

  // If the direct fetch returned a portrait or photo of a person instead of a diagram, reject it
  if (img && isPhotoOrPortrait(img.url)) {
    img = null;
  }

  // Step 2: Fuzzy search fallback if direct fetch yielded no image
  if (!img) {
    const searchedTitle = await searchWikipediaTitle(cleaned);
    if (searchedTitle && searchedTitle.toLowerCase() !== cleaned.toLowerCase()) {
      matchedTitle = searchedTitle;
      img = await tryFetchWikipediaImage(matchedTitle);
      if (img && isPhotoOrPortrait(img.url)) {
        img = null;
      }
    }
  }

  // Step 3: Wikimedia Commons diagram search fallback
  if (!img) {
    img = await tryCommonsDiagramSearch(matchedTitle);
  }

  return img;
}

/**
 * Helper to query Wikipedia REST API and MediaWiki pageimages API for a title.
 */
async function tryFetchWikipediaImage(title: string): Promise<WikiImage | null> {
  const encodedTitle = encodeURIComponent(title.replace(/ /g, "_"));

  // Try Wikipedia REST API summary
  try {
    const res = await fetch(
      `https://en.wikipedia.org/api/rest_v1/page/summary/${encodedTitle}`,
      { headers: { "Accept": "application/json" } }
    );
    if (res.ok) {
      const data = await res.json();
      const imgUrl = data.originalimage?.source || data.thumbnail?.source;
      if (imgUrl) {
        return {
          url: getWikimediaThumbnailUrl(imgUrl, 500),
          caption: data.description || title,
          sourceUrl: data.content_urls?.desktop?.page || `https://en.wikipedia.org/wiki/${encodedTitle}`,
        };
      }
    }
  } catch {}

  // Try MediaWiki pageimages API
  try {
    const apiUrl = `https://en.wikipedia.org/w/api.php?action=query&titles=${encodedTitle}&prop=pageimages&pithumbsize=500&format=json&origin=*`;
    const res = await fetch(apiUrl);
    if (res.ok) {
      const data = await res.json();
      const pages = data.query?.pages;
      if (pages) {
        const page = Object.values(pages)[0] as any;
        const thumbUrl = page?.thumbnail?.source;
        if (thumbUrl) {
          return {
            url: getWikimediaThumbnailUrl(thumbUrl, 500),
            caption: title,
            sourceUrl: `https://en.wikipedia.org/wiki/${encodedTitle}`,
          };
        }
      }
    }
  } catch {}

  return null;
}

/**
 * Helper to query Wikimedia Commons search specifically for diagram files.
 */
async function tryCommonsDiagramSearch(title: string): Promise<WikiImage | null> {
  const encodedTitle = encodeURIComponent(title.replace(/ /g, "_"));
  try {
    const searchUrl = `https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodedTitle}+diagram&gsrnamespace=6&prop=imageinfo&iiprop=url|extmetadata&format=json&origin=*`;
    const res = await fetch(searchUrl);
    if (res.ok) {
      const data = await res.json();
      const pages = data.query?.pages;
      if (pages) {
        const firstPage = Object.values(pages)[0] as any;
        const url = firstPage?.imageinfo?.[0]?.url;
        if (url && /\.(svg|png|jpg|gif|jpeg)$/i.test(url)) {
          return {
            url: getWikimediaThumbnailUrl(url, 500),
            caption: title,
            sourceUrl: `https://en.wikipedia.org/wiki/${encodedTitle}`,
          };
        }
      }
    }
  } catch {}
  return null;
}

/**
 * Fetches multiple Wikipedia images in parallel.
 * Returns a map of wikiTitle → WikiImage (or null if not found).
 */
export async function fetchMultipleWikiImages(
  suggestions: Array<{ label: string; wikiTitle: string; section: string }>
): Promise<Record<string, WikiImage | null>> {
  const results: Record<string, WikiImage | null> = {};
  await Promise.all(
    suggestions.map(async (s) => {
      results[s.wikiTitle] = await fetchWikipediaImage(s.wikiTitle);
    })
  );
  return results;
}
